/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pharma;

//import Trie;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Document;
/**
 *
 * @author Abraham Abbey Junior
 */
public class Pharmacy extends javax.swing.JFrame implements ActionListener, DocumentListener {

    /**
     * Creates new form Main
     */
    static Trie trie;
    public Pharmacy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        insert = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        search = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        input_btn = new javax.swing.JTextField();
        exit_btn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display_button = new javax.swing.JTextArea();
        maximize_btn = new javax.swing.JLabel();
        mini_btn = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(204, 204, 255));

        sidepanel.setBackground(new java.awt.Color(0, 0, 102));

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pharmacy Management System");

        insert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add List_20px.png"))); // NOI18N
        insert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Insert(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Add drug");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delete Database_20px.png"))); // NOI18N
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delet(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Delete drug");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Find Matching Job_20px.png"))); // NOI18N
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Find drug");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RooDex");

        javax.swing.GroupLayout sidepanelLayout = new javax.swing.GroupLayout(sidepanel);
        sidepanel.setLayout(sidepanelLayout);
        sidepanelLayout.setHorizontalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidepanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidepanelLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidepanelLayout.createSequentialGroup()
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(sidepanelLayout.createSequentialGroup()
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(sidepanelLayout.createSequentialGroup()
                        .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sidepanelLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(155, Short.MAX_VALUE)))
        );
        sidepanelLayout.setVerticalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(insert, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sidepanelLayout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jLabel4)
                    .addContainerGap(340, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(110, 89, 221));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search_20px.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Input");

        input_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputDrugHandler(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(input_btn))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(input_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        exit_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit_btn.setText("X");
        exit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_btnMouseClicked(evt);
            }
        });

        display_button.setColumns(20);
        display_button.setRows(5);
        jScrollPane1.setViewportView(display_button);

        maximize_btn.setBackground(new java.awt.Color(0, 0, 0));
        maximize_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        maximize_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maximize_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maximize Window_15px_9.png"))); // NOI18N
        maximize_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maximize_btnMouseClicked(evt);
            }
        });

        mini_btn.setBackground(new java.awt.Color(0, 0, 0));
        mini_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mini_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mini_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Minimize Window_15px_3.png"))); // NOI18N
        mini_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mini_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mini_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maximize_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exit_btn)
                        .addComponent(maximize_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mini_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(sidepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_btnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_btnMouseClicked

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
        String str = input_btn.getText();
        input_btn.setText("");
        List<String> words = trie.drugPrediction(str.toLowerCase());
        String content = "";
        for(int i = 0; i < words.size(); i++){
            content += (words.get(i) + "\n");
        }
        display_button.setText(content);
        
        //Trie.search(str);
       
    }//GEN-LAST:event_searchMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        String str = input_btn.getText();
        input_btn.setText("");
        List<String> words = trie.drugPrediction(str.toLowerCase());
        String content = "";
        for(int i = 0; i < words.size(); i++){
            content += (words.get(i) + "\n");
        }
        display_button.setText(content);    
        
        
        //listen for change in the text input feild to auto search contacts
        input_btn.getDocument().addDocumentListener(new DocumentListener(){
            
            public void warn(){
                String contactName = input_btn.getText();
                if(contactName != null){
                    List<String> words = trie.drugPrediction(contactName.toLowerCase());
                    String content = "";
                    for(int i = 0; i < words.size(); i++){
                        content += (words.get(i) + "\n");
                    }
                    display_button.setText(content);
                }else{
                    JOptionPane.showMessageDialog(null, "Error: Please enter a valid contact name",
                            contactName, JOptionPane.ERROR_MESSAGE);
                }
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                warn();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                warn();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                warn();
            }
        });// End of method to listen for change in contact input text
         
    }//GEN-LAST:event_jLabel9MouseClicked

    private void inputDrugHandler(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputDrugHandler
        // TODO add your handling code here:
        //listen for change in the text input feild to auto search contacts
        input_btn.getDocument().addDocumentListener(new DocumentListener(){
            
            public void warn(){
                String contactName = input_btn.getText();
                if(contactName == null ){
                    JOptionPane.showMessageDialog(null, "Error: Please enter a valid contact name",
                            contactName, JOptionPane.ERROR_MESSAGE);
                }else{
                    List<String> words = trie.drugPrediction(contactName.toLowerCase());
                    String content = "";
                    for(int i = 0; i < words.size(); i++){
                        content += (words.get(i) + "\n");
                    }
                    display_button.setText(content);
                }
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                warn();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                warn();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                warn();
            }
        });// End of method to listen for change in contact input text
    }//GEN-LAST:event_inputDrugHandler

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        String newContactName = input_btn.getText();
        if(newContactName != null){
            trie.addDrug(newContactName);
            
            JOptionPane.showMessageDialog(null, newContactName + " has been added successfully.",
                            newContactName, JOptionPane.ERROR_MESSAGE);
        
        }else{
                JOptionPane.showMessageDialog(null, "Soory! You cannot add an empty input!!!. Try again",
                            newContactName, JOptionPane.ERROR_MESSAGE);
            }
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        String drugNameToDelete = input_btn.getText();
        if(drugNameToDelete != null && !drugNameToDelete.isBlank()){
            boolean drugDeleteStatus = trie.deleteDrug(drugNameToDelete.trim());
            if (drugDeleteStatus){
                JOptionPane.showMessageDialog(null, drugNameToDelete + " has been deleted successfully.",
                            drugNameToDelete, JOptionPane.ERROR_MESSAGE);
                display_button.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Sorry! " +drugNameToDelete + " was not found.",
                            drugNameToDelete, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void maximize_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximize_btnMouseClicked
        // TODO add your handling code here:
        
        
        if (this.getExtendedState()!= Pharmacy.MAXIMIZED_BOTH){
            this.setExtendedState(Pharmacy.MAXIMIZED_BOTH);
        }else{
            
        this.setExtendedState(Pharmacy.NORMAL);
        }
        
    }//GEN-LAST:event_maximize_btnMouseClicked

    private void mini_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini_btnMouseClicked
        // TODO add your handling code here:
        
        this.setExtendedState(Pharmacy.ICONIFIED);
    }//GEN-LAST:event_mini_btnMouseClicked

    private void Insert(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Insert
        // TODO add your handling code here:
        String newContactName = input_btn.getText();
        if(newContactName != null){
            trie.addDrug(newContactName);
            
            JOptionPane.showMessageDialog(null, newContactName + " has been added successfully.",
                            newContactName, JOptionPane.ERROR_MESSAGE);
        
        }else{
                JOptionPane.showMessageDialog(null, "Soory! You cannot add an empty input!!!. Try again",
                            newContactName, JOptionPane.ERROR_MESSAGE);
            }
        
    }//GEN-LAST:event_Insert

    private void delet(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delet
        // TODO add your handling code here:
        String drugNameToDelete = input_btn.getText();
        if(drugNameToDelete != null && !drugNameToDelete.isBlank()){
            boolean drugDeleteStatus = trie.deleteDrug(drugNameToDelete.trim());
            if (drugDeleteStatus){
                JOptionPane.showMessageDialog(null, drugNameToDelete + " has been deleted successfully.",
                            drugNameToDelete, JOptionPane.ERROR_MESSAGE);
                display_button.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Sorry! " +drugNameToDelete + " was not found.",
                            drugNameToDelete, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_delet

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     trie = new Trie();
     trie.addDrug("abilify"); 
     trie.addDrug("acetaminophen"); 
     trie.addDrug("actos");     
     trie.addDrug("acyclovir"); 
     trie.addDrug("adderall");
     trie.addDrug("adderall XR");
     trie.addDrug("advair Diskus");
     trie.addDrug("aerosols");
     trie.addDrug("agaric");
     trie.addDrug("alpha-methyltryptamine");
     trie.addDrug("amani");
     trie.addDrug("amphetamine");
     trie.addDrug("amsterdam-gold");
     trie.addDrug("amt freebase");
     trie.addDrug("amyls");
     trie.addDrug("anabolic steroids");
     trie.addDrug("angel dust");
     trie.addDrug("annihilation");
     trie.addDrug("annihilation");
     trie.addDrug("annihilation");
     trie.addDrug("atropine"); 
     trie.addDrug("atenolol");
     trie.addDrug("ayahuasca");
     trie.addDrug("azithromycin");
     trie.addDrug("baccy");
     trie.addDrug("bacitracin"); 
     trie.addDrug("baclofen");  
     trie.addDrug("bactrim");     
     trie.addDrug("bactrim DS"); 
     trie.addDrug("bactroban");
     trie.addDrug("ballons Nitrous oxide");
     trie.addDrug("banshee dust");
     trie.addDrug("basaglar");
     trie.addDrug("base");
     trie.addDrug("bath salts");
     trie.addDrug("Beans ecstasy");
     trie.addDrug("belbuca");
     trie.addDrug("belsomra");
     trie.addDrug("benzo fury");
     trie.addDrug("benzodiazepines");
     trie.addDrug("benzofuran compounds");
     trie.addDrug("bhang");
     trie.addDrug("billy");
     trie.addDrug("blast");
     trie.addDrug("blotter");
     trie.addDrug("blow");
     trie.addDrug("blue blue");
     trie.addDrug("bolts extra");
     trie.addDrug("bom-25");
     trie.addDrug("bonsai supersleep");
     trie.addDrug("booze");
     trie.addDrug("brownnies");
     trie.addDrug("brilinta"); 
     trie.addDrug("bud cannabis");
     trie.addDrug("bumex");
     trie.addDrug("burst methylphenidate");
     trie.addDrug("cannabis");
     trie.addDrug("carfentanyl");
     trie.addDrug("cathinones");
     trie.addDrug("chang");
     trie.addDrug("charge");
     trie.addDrug("codeine - caffeine"); 
     trie.addDrug("cabazitaxel (Jevtana)");     
     trie.addDrug("cabergoline (CO Cabergoline, Dostinex)"); 
     trie.addDrug("cabometyx (cabozantinib)");
     trie.addDrug("cabozantinib (Cabometyx)");
     trie.addDrug("caduet (amlodipine - atorvastatin)");
     trie.addDrug("chargers");
     trie.addDrug("charlie cocaine");
     trie.addDrug("chat khat");
     trie.addDrug("chicken yellow");
     trie.addDrug("ching methylphenidate");
     trie.addDrug("chroming");
     trie.addDrug("clockwork orange");
     trie.addDrug("co-codamol");
     trie.addDrug("codis500");
     trie.addDrug("coke");
     trie.addDrug("cosmic kelly");
     trie.addDrug("cowies");
     trie.addDrug("crack");
     trie.addDrug("crystal estacy");
     trie.addDrug("crystal meth");
     trie.addDrug("dabigatran (Pradaxa)"); 
     trie.addDrug("dabrafenib (Tafinlar)"); 
     trie.addDrug("dacarbazine (Dacarbazine for Injection BP)"); 
     trie.addDrug("dacarbazine for Injection BP (dacarbazine)"); 
     trie.addDrug("daclatasvir (Daklinza)");     
     trie.addDrug("daclizumab (Zinbryta)"); 
     trie.addDrug("dactinomycin (Cosmegen");
     trie.addDrug("daklinza (daclatasvir)");
     trie.addDrug("diclofenac");
     trie.addDrug("d2pm");
     trie.addDrug("depas");
     trie.addDrug("desoxypipradol");
     trie.addDrug("dezolam");
     trie.addDrug("dezolam");
     trie.addDrug("diamorphine");
     trie.addDrug("diazepam");
     trie.addDrug("dimethocaine");
     trie.addDrug("dimitri");
     trie.addDrug("dizzle");
     trie.addDrug("dmt");
     trie.addDrug("dolphins");
     trie.addDrug("donkey dust");
     trie.addDrug("dope");
     trie.addDrug("dots");
     trie.addDrug("double stacked");
     trie.addDrug("downers");
     trie.addDrug("dr death pma");
     trie.addDrug("drone");
     trie.addDrug("drop lsd");
     trie.addDrug("dustinf");
     trie.addDrug("echinacea");
     trie.addDrug("eclipse salvia");
     trie.addDrug("ecotrin");
     trie.addDrug("ecsess");
     trie.addDrug("ecstacy");
     trie.addDrug("effexor"); 
     trie.addDrug("effexor XR"); 
     trie.addDrug("effient"); 
     trie.addDrug("elavil"); 
     trie.addDrug("elidel");     
     trie.addDrug("eligard");
     trie.addDrug("energy-1");
     trie.addDrug("esp piperazines");
     trie.addDrug("ethylphenidate");
     trie.addDrug("eticalm");
     trie.addDrug("etilaam");
     trie.addDrug("etisedan");
     trie.addDrug("etizola");
     trie.addDrug("etizolam");
     trie.addDrug("etisedan");
     trie.addDrug("euphoria");
     trie.addDrug("evoke");
     trie.addDrug("exodus");
     trie.addDrug("exodus Damnation");
     trie.addDrug("fags");
     trie.addDrug("famotidine");
     trie.addDrug("famotidine");
     trie.addDrug("farxiga");
     trie.addDrug("fast lane");
     trie.addDrug("febuxostat");
     trie.addDrug("femara");
     trie.addDrug("fenofibrate"); 
     trie.addDrug("fentanyl"); 
     trie.addDrug("fenazepam"); 
     trie.addDrug("flake"); 
     trie.addDrug("flash"); 
     trie.addDrug("freebase");
     trie.addDrug("frenzy");
     trie.addDrug("gabapentin");
     trie.addDrug("gbl");
     trie.addDrug("gases");
     trie.addDrug("geebs");
     trie.addDrug("gebedol");
     trie.addDrug("glue sniffing");
     trie.addDrug("glues aerosols");
     trie.addDrug("gogaine");
     trie.addDrug("grass");
     trie.addDrug("green ketamine");
     trie.addDrug("happy pills");
     trie.addDrug("hash");
     trie.addDrug("hashish");
     trie.addDrug("hawk lsd");
     trie.addDrug("herb");
     trie.addDrug("heroin");
     trie.addDrug("hippie crack");
     trie.addDrug("hookah");
     trie.addDrug("horse");
     trie.addDrug("hubble huffing");
     trie.addDrug("indopan");
     trie.addDrug("inhalants");
     trie.addDrug("inxity");
     trie.addDrug("ivory wave");
     trie.addDrug("jellies");
     trie.addDrug("juice steroids");
     trie.addDrug("ket");
     trie.addDrug("ketamine");
     trie.addDrug("khat");
     trie.addDrug("kix");
     trie.addDrug("legal E");
     trie.addDrug("leberties");
     trie.addDrug("liberties");
     trie.addDrug("liberty caps");
     trie.addDrug("linctus");
     trie.addDrug("liquid acid");
     trie.addDrug("liquid gold");
     trie.addDrug("linctus");
     trie.addDrug("lyrica");
     trie.addDrug("m-smack");
     trie.addDrug("magic crystals");
     trie.addDrug("magic mushrooms");
     trie.addDrug("magics");
     trie.addDrug("methadone");
     trie.addDrug("methamphetamine");
     trie.addDrug("mexixan magic mint");
     trie.addDrug("micro dot");
     trie.addDrug("miow");
     trie.addDrug("morphine");
     trie.addDrug("moxy");
     trie.addDrug("mushies");
     trie.addDrug("naphyrone");
     trie.addDrug("nemesis");
     trie.addDrug("neurotin");
     trie.addDrug("nootropics");
     trie.addDrug("nopaine");
     trie.addDrug("norries");
     trie.addDrug("noz");
     trie.addDrug("nrg1");
     trie.addDrug("nurofen plus/Max");
     trie.addDrug("panadol extra");
     trie.addDrug("paracetamol");
     trie.addDrug("pasaden");
     trie.addDrug("paste");
     trie.addDrug("peace pills");
     trie.addDrug("penecillin V");
     trie.addDrug("peyote");
     trie.addDrug("phenazepam");
     trie.addDrug("piperazines");
     trie.addDrug("poppers");
     trie.addDrug("pregabalin");
     trie.addDrug("propylphenidate");
     trie.addDrug("purple wave");
     trie.addDrug("pyrovalerone");
     trie.addDrug("qaadka");
     trie.addDrug("rave");
     trie.addDrug("red mitsubishi");
     trie.addDrug("resin");
     trie.addDrug("rhino ket");
     trie.addDrug("ritalin");
     trie.addDrug("rock hard");
     trie.addDrug("rohypnol");
     trie.addDrug("roids");
     trie.addDrug("rollies");
     trie.addDrug("sensi");
     trie.addDrug("shrooms");
     trie.addDrug("sildenafil");
     trie.addDrug("skag");
     trie.addDrug("syrup");
     trie.addDrug("tab");
     trie.addDrug("thrust");
     trie.addDrug("tobacco");
     trie.addDrug("tramadol");
     trie.addDrug("tramal");
     trie.addDrug("tripper");
     trie.addDrug("trips");
     trie.addDrug("tryptamines");
     trie.addDrug("ultram");
     trie.addDrug("valium");
     trie.addDrug("vallies");
     trie.addDrug("viagra");
     trie.addDrug("vitaminK");
     trie.addDrug("wash");
     trie.addDrug("whippets");
     trie.addDrug("whizz");
     trie.addDrug("window LSD");
     trie.addDrug("wonk");
     trie.addDrug("xanax");
     trie.addDrug("xtc");
     trie.addDrug("yaba");
     trie.addDrug("zoly");
     trie.addDrug("zinc tablet");
    
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Pharmacy().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel delete;
    private javax.swing.JTextArea display_button;
    private javax.swing.JLabel exit_btn;
    private javax.swing.JTextField input_btn;
    private javax.swing.JLabel insert;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel maximize_btn;
    private javax.swing.JLabel mini_btn;
    private javax.swing.JLabel search;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void insertUpdate(DocumentEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
}
